### ISSUE TITLE
key.conf with too many workspace keybindings makes snapwm crash on startup

### ISSUE THREAD

**Issue by Bollino** [moetunes/snapwm-stable#4]
This is not a really big problem, but with snapwm being feature-complete for my personal requirements, it would be nice to see the existing features working flawlessly. Stickying windows is not that important for me, but when I tried to integrate that feature in my configuration I stumbled upon what seems to be a bug:

If you uncomment the line
`#KEY Alt;5;change_desktop;4;`
snapwm will crash on startup.

`# (excerpt from key.conf)`
`KEY Alt;1;change_desktop;0; `
`KEY Alt;2;change_desktop;1;`
`KEY Alt;3;change_desktop;2;`
`KEY Alt;4;change_desktop;3;`
`#KEY Alt;5;change_desktop;4;`
`KEY Alt;6;change_desktop;5;`
`KEY Alt;7;change_desktop;6;`
`KEY Alt;8;change_desktop;7;`
`KEY Alt;9;change_desktop;8;`
`KEY Alt;0;change_desktop;9;`
`KEY Alt;minus;change_desktop;10;`
`KEY Alt;equal;change_desktop;11;`
`#`
`KEY Super;Right;rotate_desktop;1;`
`KEY Super;Left;rotate_desktop;-1;`
`#`
`#`
`KEY ShftAlt;1;follow_client_to_desktop;0;`
`KEY ShftAlt;2;follow_client_to_desktop;1;`
`KEY ShftAlt;3;follow_client_to_desktop;2;`
`KEY ShftAlt;4;follow_client_to_desktop;3;`
`KEY ShftAlt;5;follow_client_to_desktop;4;`
`KEY ShftAlt;6;follow_client_to_desktop;5;`
`KEY ShftAlt;7;follow_client_to_desktop;6;`
`KEY ShftAlt;8;follow_client_to_desktop;7;`
`KEY ShftAlt;9;follow_client_to_desktop;8;`
`KEY ShftAlt;0;follow_client_to_desktop;9;`
`KEY ShftAlt;minus;follow_client_to_desktop;10;`
`KEY ShftAlt;equal;follow_client_to_desktop;11;`
`#`
`#`
`KEY ShftSuper;1;client_to_desktop;0;`
`KEY ShftSuper;2;client_to_desktop;1;`
`KEY ShftSuper;3;client_to_desktop;2;`
`KEY ShftSuper;4;client_to_desktop;3;`
`KEY ShftSuper;5;client_to_desktop;4;`
`KEY ShftSuper;6;client_to_desktop;5;`
`KEY ShftSuper;7;client_to_desktop;6;`
`KEY ShftSuper;8;client_to_desktop;7;`
`KEY ShftSuper;9;client_to_desktop;8;`
`KEY ShftSuper;0;client_to_desktop;9;`
`KEY ShftSuper;minus;client_to_desktop;10;`
`KEY ShftSuper;equal;client_to_desktop;11;`
`#`
`#`
`KEY AltSuper;1;sticky_win;1;`
`KEY AltSuper;2;sticky_win;2;`
`KEY AltSuper;3;sticky_win;3;`
`KEY AltSuper;4;sticky_win;4;`
`KEY AltSuper;5;sticky_win;5;`
`KEY AltSuper;6;sticky_win;6;`
`KEY AltSuper;7;sticky_win;7;`
`KEY AltSuper;8;sticky_win;8;`
`KEY AltSuper;9;sticky_win;9;`
`KEY AltSuper;10;sticky_win;10;`
`KEY AltSuper;minus;sticky_win;11;`
`KEY AltSuper;equal;sticky_win;12;`
`#`
`KEY AltSuper;s;unsticky_win;`

Comment that line out again - or any other of the workspace-related KEY lines - and snapwm will start just fine (obviously minus that one keybinding). Doesn't really matter, which line you comment out or delete in the change_desktop, follow_client_to_desktop, client_to_desktop or sticky_win sections. So the problem seems to be related to the **number** of KEY lines. I had the idea it could be a side-effect of your switch from counting 0...n with the old functions to counting 1...n+1 with the "new" sticky_win function. But what do I know, I'm not a programmer. Any idea? TIA

**Comment by moetunes** [comment]
Sorry for the slow reply.
Try changing line 247 in snapwm.c to
static key keys[120];
rebuild and try with all your shortcuuts.
If it works for you I'll push it to here.
Cheers

**Comment by Bollino** [comment]
Hi moetunes,
that "patch" works fine, thank you. It's a shame that this wm seems to fly under the radar compared to others like i3, bspwm, awesome or even spectrwm. I appreciate that you still monitor user comments.
Cheers
